### ISSUE TITLE
Issue with Voltage for AUV7

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_power#27]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
The telemetry should display both battery voltage in the top bar and display all the right data in the power tracking section.

## Current Behavior
The output of the topic provider_power/voltage doesn't seem like it's all votlage and that it's placed correctly. Also, the voltage for both batteries are there but again the order might not be right.

## Possible Solution
Check the code for the hardware powersupply to understand the configuration of the message on RS485

## Comments
This can be easily tested at school with 2 batteries on different level of charge on AUV7.

## Environment Used
- Project version : 2.0.1

**Comment by Kam0ss** [comment]
Can you provide exactly what slave send data for what motor and battery ? 
Reading the code of interface is not enough if I can't rely on the connections with the hardware.

And if the voltage is wrong, does it mean the current is also wrong ?

**Comment by supertoto29** [comment]
Here is the exact data from the powersupplies on AUV7.

`[Motor XY, Motor Depth, 12V, Battery]`

These are the array received on Voltage and Current. To keep in mind, the float data is converted on RS485 to 4 uint8 to be sent on the bus.

**Comment by supertoto29** [comment]
Here is the organisation of the powersupplies on AUV7.

`PSU0 : [M1, M5, 12V1, Battery1]`
`PSU1 : [M2, M6, 12V2, Battery1]`
`PSU2 : [M3, M7, 12V3, Battery2]`
`PSU3 : [M1, M8, 12V4, Battery2]`

**Comment by Kam0ss** [comment]
We know where the issue might come from : we send 10 values on provider_power from AUV8 and 12 values coming from AUV7 to the telemetry, in the telemetry, we display values 9 and 10 from the data for the batteries, and we can see here : 
https://github.com/sonia-https://github.com/sonia-auv/provider_power/blob/a524c32de63103aeacbf164c890f90da089d9947/src/provider_power/provider_power_node.cc#L367-L378
That the values 9 and 10 from AUV7 are both battery 1.
We should remove lines 376 and 378 as the values there are the same than in the lines 375 and 377.

**Comment by Kam0ss** [comment]
The code was modified and is ready to be tested (branch fix/voltage).

**Comment by supertoto29** [comment]
![Screenshot from 2022-05-25 21-46-03](https://user-images.githubusercontent.com/44241055/170398338-5dfbe53a-cc9f-4569-98be-ff43a8b55b53.png)
We plugged one battery at 15.6V and one external powersupply. Code is ready for a push to develop!!! @Kam0ss
