### ISSUE TITLE
Data not consisting with the sub

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_power#39]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
The data for the voltage and current should be in sync with the sub.

## Current Behavior
The display doesn't follow the submarine

## Comments
This image is when the killswitch is pulled and it's not changing.
![Capture d’écran 2022-05-28 150158](https://user-images.githubusercontent.com/44241055/170839455-dcf7dd88-2839-4fba-ae68-9c2240a2f108.png)

## Environment Used
- Project version : 2.0.2

**Comment by Kam0ss** [comment]
I don't understand, what is it supposed to display ? And this is probably not on provider_power.

**Comment by supertoto29** [comment]
This is the data from provider_power. When the killswitch is pulled, all the voltage should drop at 0V except the battery voltage.
There is an issue with provider power keeping the previous data.

**Comment by Kam0ss** [comment]
Does the data sent from interface rs485 is all 0 or is it just not sent anymore ?
(Also this situation should be part of PFE module check)

**Comment by supertoto29** [comment]
The data might be 0 but the shared queue might create a buffer of the previous values and it won't change before the buffer isn't empty

**Comment by supertoto29** [comment]
Update on the issue :
The board will send the right data so when the killswitch is pulled. The board is sending 0V at the motors. It seems like there is some sort of a buffer because on the telemetry, one powersupply will be at 0V but the others will still be at 16V for example. It will take a few minutes before all the voltages are at 0V.
It is hard for us to debug or monitor with this behavior
